// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAABB72KuUOAERVJOjGojlr6733LToM05A',
    appId: '1:150174906687:web:16fda8e6af017bebea7b8a',
    messagingSenderId: '150174906687',
    projectId: 'globalchatapp-67cd7',
    authDomain: 'globalchatapp-67cd7.firebaseapp.com',
    storageBucket: 'globalchatapp-67cd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_6kyPf8gWOSZBmrbajV18E6lCtPSkxLM',
    appId: '1:150174906687:android:f8a97c6691e5be7dea7b8a',
    messagingSenderId: '150174906687',
    projectId: 'globalchatapp-67cd7',
    storageBucket: 'globalchatapp-67cd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeYUhMgj1HqUQDCbCIYaPZa6Qx9r0bjk',
    appId: '1:150174906687:ios:132ec07d0a422853ea7b8a',
    messagingSenderId: '150174906687',
    projectId: 'globalchatapp-67cd7',
    storageBucket: 'globalchatapp-67cd7.appspot.com',
    iosBundleId: 'com.practiceapp.chitchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmeYUhMgj1HqUQDCbCIYaPZa6Qx9r0bjk',
    appId: '1:150174906687:ios:132ec07d0a422853ea7b8a',
    messagingSenderId: '150174906687',
    projectId: 'globalchatapp-67cd7',
    storageBucket: 'globalchatapp-67cd7.appspot.com',
    iosBundleId: 'com.practiceapp.chitchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAABB72KuUOAERVJOjGojlr6733LToM05A',
    appId: '1:150174906687:web:c8d9098117022e81ea7b8a',
    messagingSenderId: '150174906687',
    projectId: 'globalchatapp-67cd7',
    authDomain: 'globalchatapp-67cd7.firebaseapp.com',
    storageBucket: 'globalchatapp-67cd7.appspot.com',
  );
}
